# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: /assets/images/icon.ico

# Content configuration version
version: 2

# Personal info
name: Gustavo Maximiano Cardoso
title: Técnico em Informática
email: guhh.cardoso1@gmail.com
# email_title: Email (Email title override)
phone: (15) 98823-9949
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  GustavoMaxCardoso
instagram_username: _gustavo_crds
linkedin_username: gustavo-cardoso-876238238


# Additional icon links
#additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mim 

about_profile_image: /images/perfil_image.jpeg
about_content: | # this will include new lines to allow paragraphs
  Sou um profissional de TI com uma paixão que começou na infância, desmontando e configurando computadores para superar seus limites. Essa curiosidade inicial por hardware evoluiu para uma carreira dedicada à infraestrutura e operações de TI, impulsionada pela crença de que nunca se sabe o suficiente e pela vontade constante de aprender.

  Minha trajetória é marcada por hands-on experience e autonomia. Após um estágio enriquecedor na prefeitura, onde dei os primeiros passos em redes, protocolos e segurança, assumi meu primeiro emprego formal como o único responsável pelo setor de TI, onde aprendi na prática a correr atrás de soluções para os mais variados desafios.
  
  Hoje, gerencio toda a infraestrutura de TI de 7 lojas, incluindo a administração de 10 servidores, redes e suporte. Minha abordagem é proativa: desenvolvi e implemento uma NOC (Network Operations Center) personalizada usando <a href="/images/zabbix_dashboard.png" target="_blank" rel="noopener noreferrer">Zabbix</a> e Grafana para monitoramento em tempo real, e estou liderando o projeto de migração e modernização da rede central, trocando dispositivos Mikrotik por Ubiquiti Cloud Ultra Gateway.

  Estou finalizando minha <a href="/images/pos_grade_curricular.jpeg" target="_blank" rel="noopener noreferrer">pós-graduação em Arquitetura de Software</a> e busco constantemente cursos e atualizações para aliar minha sólida base de infraestrutura com as melhores práticas de desenvolvimento e arquitetura de sistemas. Meu objetivo é evoluir para posições que unam a operação de TI com o planejamento estratégico, criando soluções robustas, escaláveis e que tragam resultados tangíveis.


content:
  - title: Projetos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Projeto MarktFlow
        link: https://github.com/GustavoMaxCardoso/Projeto-MarketFlow
        link_text: Link para o repositório do projeto
        description: | # this will include new lines to allow paragraphs
          Sistema completo para automação de mercados desenvolvido em Java, incluindo PDV, controle de estoque, gestão financeira e relatórios analíticos. Trabalhei no backend e frontend, aplicando arquitetura MVC e metodologias ágeis. Desenvolvido em equipe de 6 pessoas durante a faculdade, tendo experiencia de Git colaborativo.

          **Tecnologias:** Java, MySQL, Git, MVC<br>
          **Funcionalidades:** PDV, Controle de Estoque, Relatórios Financeiros
  - title: Experiência
    layout: list
    content:
      - layout: right
        title: Rede Almodovar - Fazfarma
        sub_title: Técnico em TI
        caption: Mar 2024 - Atualmente
        link: https://www.fazfarma.com.br
        quote: >
          Rede de farmácias com múltiplas unidades.
        description: | # this will include new lines to allow paragraphs
          Promovido de Auxiliar de TI para Técnico em TI em Outubro de 2025. Responsável pela infraestrutura completa de TI de 7 lojas.
        
          **Principais atividades e conquistas:**<br>
          - Gestão completa de infraestrutura: 10 servidores, redes e sistemas de segurança<br>
          - Desenvolvimento e implementação de NOC (Network Operations Center) usando Zabbix e Grafana<br>
          - Liderança do projeto de migração de rede (Mikrotik para Ubiquiti Cloud Ultra Gateway)<br>
          - Suporte técnico aos usuários e manutenção de hardware/software<br>
          - Responsável por compras e negociação de contratos do setor de TI<br>
          - Administração de sistemas e gestão de redes<br>

      - layout: right
        title: Prefeitura Municipal de Salto de Pirapora
        sub_title: Estagiário de Tecnologia da Informação
        caption: Nov 2022 - Mar 2024
        link: https://www.saltodepirapora.sp.gov.br
        quote: >
          Órgão público municipal.
        description: | # this will include new lines to allow paragraphs
          Estágio em TI com atuação em múltiplas frentes da infraestrutura tecnológica municipal.
        
          **Principais atividades:**<br>
          - Manutenção e configuração de computadores, notebooks e impressoras<br>
          - Manutenção preventiva em servidores de sites e bancos de dados SQL<br>
          - Suporte à infraestrutura de rede interna e externa ao paço municipal<br>
          - Auxílio na administração de sistemas de segurança<br>
          - Implementação de ferramentas para aumento da eficiência operacional  
  - title: Educação
    layout: list
    content:
      - layout: top-right
        title: FACENS Sorocaba
        sub_title: Pós-Graduação em Engenharia de Software
        caption: 2025 - 2027 (Previsão)
        quote: >
          Instituição de ensino superior com foco em tecnologia e engenharia
        description: | # this will include new lines to allow paragraphs
          Pós-graduação com foco em arquitetura de software, Big Data & Business Analytics, Methodologies Agile Project Management & Digital Product, 	Ux Design & Digital Experience, Cloud Computing, 	Cyber Security in Applications, DevOps, 	Full Stack Developer e Machine Learning & Deep Learning. Previsão de conclusão para o 1º semestre de 2027.<br>

      - layout: top-right
        title: FACENS Sorocaba
        sub_title: Graduação em Análise e Desenvolvimento de Sistemas
        caption: 2022 - 2024
        quote: >
          Instituição de ensino superior com foco em tecnologia e engenharia
        description: | # this will include new lines to allow paragraphs
          Graduação focada em desenvolvimento de software, banco de dados, engenharia de requisitos e gestão de projetos. Concluída com êxito no 2º semestre de 2024.<br> <a href="/assets/documents/Diploma_Facens.PDF" target="_blank" rel="noopener noreferrer"><strong>Certificado de Conclusão</strong></a>
   
  - title: Um pouco mais sobre mim
    layout: text
    content: | # this will include new lines to allow paragraphs
          **CERTIFICAÇÕES E QUALIFICAÇÕES**<br>
          - **UDEMY:** Certificado em CFL-C02, CCNA 200-301 e SQL Server<br>
          - **Instituto Brasileiro de Cibersegurança (IBSEC):** Certificado em IC-INF-1970<br>
          - Demonstrado comprometimento contínuo com o aprimoramento profissional através de certificações especializadas<br>

          **HABILIDADES TÉCNICAS**<br>
    
          **Linguagens de Programação:**<br>
          - Python e Java<br>

          **Desenvolvimento Web:**<br>
          - HTML5, CSS3, JavaScript<br>
          - Frameworks: Angular, Node.js, React<br>

          **Banco de Dados:**<br>
          - MySQL, SQL Server, MongoDB<br>

          **Ferramentas e Tecnologias:**<br>
          - IDEs: VSCode<br>
          - Frameworks: Spring Boot, React, Angular<br>
          - Controle de Versão: Git<br>
          - Gerenciamento de Projetos: JIRA<br>
          - Banco de Dados: MongoDB Compass<br>

          **Competências Comportamentais**<br>
          - Autodidata e proativo na busca por novos conhecimentos<br>
          - Capacidade de trabalhar em equipe e comunicar ideias técnicas<br>
          - Adaptabilidade para aprender novas tecnologias rapidamente

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
